# Generated by Django 4.1.1 on 2022-10-22 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted_user',
            field=models.BooleanField(default=False, verbose_name='Is deleted user'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
